name: northstar
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - pyg>=2.2.0
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pandas
  - seaborn
  - jinja2
  - tqdm
  - joblib
  - rich
  - textual
  - python-dotenv
  - mypy
  - black
  - pylint
  - simplejson
  - pyproj